# Generated by Django 4.1.1 on 2022-09-22 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ism")),
                (
                    "age",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Yosh"),
                ),
                ("description", models.TextField(verbose_name="Tavsifi")),
                (
                    "image",
                    models.ImageField(upload_to="actors/", verbose_name="Tasvirlar"),
                ),
            ],
            options={
                "verbose_name": "Aktyor va rejissor",
                "verbose_name_plural": "Aktyor va rejissor",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Kategoriya")),
                ("description", models.TextField(verbose_name="tavsifi")),
                ("url", models.SlugField(max_length=160)),
            ],
            options={"verbose_name": "Kategoriya", "verbose_name_plural": "Kategoriy",},
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ism")),
                ("description", models.TextField(verbose_name="Tavsifi")),
                ("url", models.SlugField(max_length=100, unique=True)),
            ],
            options={"verbose_name": "Janr", "verbose_name_plural": "Janr",},
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Nomlash")),
                (
                    "tagline",
                    models.CharField(default="", max_length=100, verbose_name="shiori"),
                ),
                ("description", models.TextField(verbose_name="Tavsifi")),
                (
                    "poster",
                    models.ImageField(upload_to="movies/", verbose_name="Afisha"),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        default=2019, verbose_name="Ma'lumotlarni kiritish"
                    ),
                ),
                ("cauntry", models.CharField(max_length=30, verbose_name="Sahifa")),
                (
                    "world_premiere",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Jahon premyerasi"
                    ),
                ),
                (
                    "budget",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="dollar miqdorini kiriting",
                        verbose_name="Byudjet",
                    ),
                ),
                (
                    "fees_in_usa",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="dollar miqdorini kiriting",
                        verbose_name="AQSh to'lovlari",
                    ),
                ),
                (
                    "fees_in_world",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="dollar miqdorini kiriting",
                        verbose_name="Dunyodagi to'lovlar",
                    ),
                ),
                ("url", models.SlugField(max_length=160, unique=True)),
                ("draft", models.BooleanField(default=False, verbose_name="Qoralama")),
                (
                    "actors",
                    models.ManyToManyField(
                        related_name="kino_aktyor",
                        to="movies.actor",
                        verbose_name="aktyor",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="movies.category",
                        verbose_name="Kategoriya",
                    ),
                ),
                (
                    "derectors",
                    models.ManyToManyField(
                        related_name="kino_rejissyor",
                        to="movies.actor",
                        verbose_name="rejissor",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(to="movies.genre", verbose_name="janr"),
                ),
            ],
            options={"verbose_name": "Kino", "verbose_name_plural": "Kino",},
        ),
        migrations.CreateModel(
            name="RatingStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Manosi"),
                ),
            ],
            options={
                "verbose_name": "Reyting yulduzi",
                "verbose_name_plural": "Reyting yulduzi",
            },
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=100, verbose_name="Ism")),
                ("text", models.TextField(max_length=5000, verbose_name="Xabar")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                        verbose_name="Kino",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="movies.reviews",
                        verbose_name="Ota-ona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ko‘rib chiqish",
                "verbose_name_plural": "Ko‘rib chiqish",
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=15, verbose_name="IP manzili")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.fields.CharField,
                        to="movies.movie",
                        verbose_name="kino",
                    ),
                ),
                (
                    "star",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.ratingstar",
                        verbose_name="yulduz",
                    ),
                ),
            ],
            options={"verbose_name": "Reyting", "verbose_name_plural": "Reyting",},
        ),
        migrations.CreateModel(
            name="MovieShots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Sarlavha")),
                ("description", models.TextField(verbose_name="Tavsifi")),
                (
                    "image",
                    models.ImageField(upload_to="movie_shots/", verbose_name="Tasvir"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                        verbose_name="Kino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kino ramka",
                "verbose_name_plural": "Kino ramka",
            },
        ),
    ]
